"""
Briefing output formatters — Markdown, HTML, and PDF.
"""

import logging
from datetime import datetime

from agents.briefing.generator import Briefing

logger = logging.getLogger(__name__)


class BriefingFormatter:
    """Format briefings into various output formats."""

    @staticmethod
    def format_markdown(briefing: Briefing) -> str:
        """Format briefing as Markdown."""
        lines = [
            f"# {briefing.title}",
            "",
            f"**Classification**: {briefing.classification}",
            f"**Generated**: {briefing.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"**Type**: {briefing.briefing_type.replace('_', ' ').title()}",
        ]
        if briefing.region_id:
            lines.append(f"**Region**: {briefing.region_id}")
        lines.append(f"**Time Window**: {briefing.time_window}")
        lines.append("")
        lines.append("---")
        lines.append("")

        for section in sorted(briefing.sections, key=lambda s: -s.priority):
            lines.append(f"## {section.title}")
            lines.append("")
            lines.append(section.content)
            lines.append("")

        lines.append("---")
        lines.append(f"*Generated by TerraCube Sentinel Intelligence Platform*")
        return "\n".join(lines)

    @staticmethod
    def format_html(briefing: Briefing) -> str:
        """Format briefing as HTML page with dark theme styling."""
        sections_html = ""
        for section in sorted(briefing.sections, key=lambda s: -s.priority):
            content = section.content.replace("\n", "<br>")
            content = content.replace("**", "<strong>").replace("**", "</strong>")
            sections_html += f"""
            <div class="section">
                <h2>{section.title}</h2>
                <div class="content">{content}</div>
            </div>"""

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{briefing.title}</title>
    <style>
        body {{
            font-family: 'Inter', -apple-system, sans-serif;
            background: #0b1120;
            color: #e2e8f0;
            max-width: 900px;
            margin: 0 auto;
            padding: 2rem;
            line-height: 1.6;
        }}
        h1 {{
            color: #38bdf8;
            border-bottom: 2px solid #1e3a5f;
            padding-bottom: 0.5rem;
        }}
        h2 {{
            color: #7dd3fc;
            margin-top: 1.5rem;
        }}
        .meta {{
            color: #94a3b8;
            font-size: 0.9rem;
            margin-bottom: 1.5rem;
        }}
        .section {{
            background: #0f172a;
            border: 1px solid #1e293b;
            border-radius: 8px;
            padding: 1rem 1.5rem;
            margin-bottom: 1rem;
        }}
        .content {{
            white-space: pre-wrap;
        }}
        strong {{ color: #fbbf24; }}
        hr {{ border-color: #1e293b; }}
        .footer {{
            text-align: center;
            color: #64748b;
            font-size: 0.8rem;
            margin-top: 2rem;
        }}
    </style>
</head>
<body>
    <h1>{briefing.title}</h1>
    <div class="meta">
        <p>Classification: {briefing.classification} |
           Generated: {briefing.generated_at.strftime('%Y-%m-%d %H:%M UTC')} |
           Type: {briefing.briefing_type.replace('_', ' ').title()}</p>
    </div>
    {sections_html}
    <hr>
    <div class="footer">Generated by TerraCube Sentinel Intelligence Platform</div>
</body>
</html>"""

    @staticmethod
    def format_pdf(briefing: Briefing) -> bytes | None:
        """Format briefing as PDF. Requires reportlab."""
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.colors import HexColor
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            from io import BytesIO

            buffer = BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=A4)
            styles = getSampleStyleSheet()

            title_style = ParagraphStyle(
                "BriefTitle", parent=styles["Title"],
                textColor=HexColor("#38bdf8"), fontSize=16,
            )
            heading_style = ParagraphStyle(
                "BriefHeading", parent=styles["Heading2"],
                textColor=HexColor("#7dd3fc"), fontSize=13,
            )
            body_style = ParagraphStyle(
                "BriefBody", parent=styles["Normal"],
                textColor=HexColor("#e2e8f0"), fontSize=10,
            )

            story = []
            story.append(Paragraph(briefing.title, title_style))
            story.append(Spacer(1, 12))
            meta = (
                f"Classification: {briefing.classification} | "
                f"Generated: {briefing.generated_at.strftime('%Y-%m-%d %H:%M UTC')}"
            )
            story.append(Paragraph(meta, body_style))
            story.append(Spacer(1, 20))

            for section in sorted(briefing.sections, key=lambda s: -s.priority):
                story.append(Paragraph(section.title, heading_style))
                story.append(Spacer(1, 6))
                content = section.content.replace("\n", "<br/>")
                story.append(Paragraph(content, body_style))
                story.append(Spacer(1, 12))

            doc.build(story)
            return buffer.getvalue()
        except ImportError:
            logger.warning("reportlab not installed — PDF generation unavailable")
            return None
